image: alpine

stages:
  # - build
  # - test
  - sync # push the project from gitlab to github

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.

# note: this job only pushes branches and tags, not issues & pull requests
# all the github remotes urls must be placed into "docs/pipelineConfigs/.cd-remotes" file
sync-repositories:
  stage: sync
  script:
    - apk add --no-cache git
    # debug stuffs
    - git branch -a
    - git tag -l
    - git log --oneline -5
    - git remote -v
    - git clone --mirror "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" temp-mirror
    - cd temp-mirror
    - ls -ali ../
    - |
      while IFS= read -r line
      do
        echo "$line" | IFS=':' read -r remote_item custom_ci_var_name # retreives the 2 values from 
        custom_token_value="${!custom_ci_var_name}" # retreiving real token value with indirect references
        echo "Pushing to: https://$custom_token_value@github.com/$remote_item"
        git push --mirror --force "https://$custom_token_value@github.com/$remote_item"
      done < ../pipelineConfigs/.cd-remotes
    - |